# Generated by Django 2.0.1 on 2018-01-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_final',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
    ]
