# Generated by Django 2.0.1 on 2018-01-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='DOJ',
            new_name='years_of_experience',
        ),
    ]
